name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Docker Buildx (a tool for building multi-platform images)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Cache Docker layers to speed up the build process
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      # Log into Docker Hub using GitHub Secrets
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and push the Docker image
      - name: Build and push Docker image
        run: |
          # Ensure we are specifying the correct Dockerfile path
          docker build -f PaymentAPI/Dockerfile -t ${{ secrets.DOCKERHUB_USERNAME }}dockerpaymentapi:${{ github.sha }} .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}dockerpaymentapi:${{ github.sha }}

      # Optional: Tag the image as 'latest'
      - name: Tag image as latest
        run: |
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}dockerpaymentapi:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}dockerpaymentapi:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}dockerpaymentapi:latest
