# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore PaymentAPI.sln

    - name: Build
      run: dotnet build PaymentAPI.sln

    - name: Test
      run: dotnet test --no-build --verbosity normal
    
    # Build the Docker image but don't push it yet
    - name: Build Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .
        dockerfile: Dockerfile
        push: false
        tags: ${{ secrets.DOCKER_USERNAME }}paymentapi:latest  # Fixed tag format

    # Login to Docker Hub using access token
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Push the Docker image to Docker Hub
    - name: Push to Docker Hub
      uses: docker/build-push-action@v2
      with:
        context: .
        dockerfile: Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}paymentapi:latest  # Fixed tag format
